apiVersion: v1
kind: Service
metadata:
  name: svc-puppet-server
spec:
  type: NodePort
  ports:
    - port: 8140
      name: puppet-port
      targetPort: 8140
  selector:
    app: puppet-server.local